### ISSUE TITLE
Always shows options[0] text after init

### ISSUE THREAD

**Issue by hardikdabhi** [shootthebit/stb-dropdown#1]
Instead of showing text of option which is marked "selected" from select tag, it always choses **$options[0]** text while initiating.

change the below line,
`$currentContainer.find('.selected').text($($options[0]).text());`
to
`$currentContainer.find('.selected').text($el.children("option").filter(":selected").text());`

This is what I've changed to fix this issue. Now it displays selected option while initiating dropdown.

**Comment by lvalencia** [comment]
Thanks for the report, this was an issue we've been meaning to fix. 
The behavior you expect is now exhibited by v1.0.1. Enjoy.
